'use client';

import React, { useState } from 'react';
import type { DecisionRecord } from '@/lib/data/types';
import { Panel } from '@/design/components/Panel';
import { Tabs } from '@/design/components/Tabs';
import { KeyValue } from '@/design/components/KeyValue';
import { CheckRow } from '@/design/components/CheckRow';
import { ProvenanceLine } from '@/design/components/ProvenanceLine';
import { CellVoltageChart } from '@/features/charts/CellVoltageChart';

export function ModelPanel({ record }: { record: DecisionRecord }) {
  const [tab, setTab] = useState('identity');
  const identity = record.modelIdentity;

  return (
    <Panel title="Model assurance" subtitle={record.layers.model.summary} className="h-full">
      <Tabs
        items={[
          { id: 'identity', label: 'Model identity' },
          { id: 'checks', label: 'Assurance checks' },
          { id: 'card', label: 'Supplied model card' },
          { id: 'summary', label: 'Summary' },
        ]}
        active={tab}
        onChange={setTab}
      />
      <div className="mt-3 flex flex-col gap-3">
        {tab === 'identity' && (
          <div>
            {!identity.matches && (
              <p className="text-[13px] text-[var(--limitation-ink)] bg-[var(--limitation-bg)] border border-[var(--limitation-border)] rounded-[var(--r-sm)] px-3 py-2 mb-3">
                Incoming {identity.incomingVersion} against configured {identity.configuredProduction}. The result cannot be confirmed as generated by the approved production model.
              </p>
            )}
            <div className="grid grid-cols-2 gap-x-4">
              <KeyValue label="Incoming model version" value={identity.incomingVersion} mono />
              <KeyValue label="Configured production model" value={identity.configuredProduction} mono />
              <KeyValue label="Match state" value={identity.matches ? 'Matches production' : 'Does not match production'} />
              <KeyValue label="Manufacturer" value={identity.manufacturer} />
              <KeyValue label="Assurance engine" value={identity.assuranceEngine} mono />
              <KeyValue label="Policy set" value={identity.policySet.join(', ')} />
            </div>
          </div>
        )}
        {tab === 'checks' && record.layers.model.checks.map((check) => <CheckRow key={check.id} check={check} />)}
        {tab === 'card' && (
          <div>
            <ProvenanceLine provenance="supplied" note={record.suppliedModelCard.provenanceNote} />
            <div className="grid grid-cols-2 gap-x-4 mt-2">
              {record.suppliedModelCard.entries.map((entry) => (
                <KeyValue key={entry.label} label={entry.label} value={entry.value} />
              ))}
            </div>
          </div>
        )}
        {tab === 'summary' && <CellVoltageChart rows={record.telemetry} />}
      </div>
      <p className="mt-3 text-[12px] text-[var(--ink-3)]">
        CCE verifies model identity and output integrity. It does not inspect model internals.
      </p>
    </Panel>
  );
}
