'use client';

import React, { useState } from 'react';
import { DecisionRecord } from '@/lib/data/types';
import { Panel } from '@/design/components/Panel';
import { Tabs } from '@/design/components/Tabs';
import { KeyValue } from '@/design/components/KeyValue';
import { CheckRow } from '@/design/components/CheckRow';
import { StatusBadge } from '@/design/components/StatusBadge';
import { ProvenanceLine } from '@/design/components/ProvenanceLine';
import { C7CellVoltageDistribution } from '@/features/charts/C7CellVoltageDistribution';

export interface ModelAssurancePanelProps {
  record: DecisionRecord;
}

export function ModelAssurancePanel({ record }: ModelAssurancePanelProps) {
  const [activeTab, setActiveTab] = useState('identity');

  const layer = record.layers.model;
  const modelId = record.modelIdentity;
  const modelCard = record.suppliedModelCard;

  const tabs = [
    { id: 'identity', label: 'Model Identity' },
    { id: 'checks', label: 'Assurance Checks' },
    { id: 'card', label: 'Supplied Model Card' },
    { id: 'summary', label: 'Summary' },
  ];

  const isMismatch = !modelId.matches || modelId.incomingVersion !== modelId.configuredProduction;

  return (
    <Panel
      title="Layer 2: Model Assurance"
      subtitle={`Model identity, version alignment & inference integrity for ${record.batteryId}`}
      actions={<StatusBadge status={layer.result} size="md" />}
      className="flex flex-col flex-1 h-full"
    >
      <Tabs items={tabs} active={activeTab} onChange={setActiveTab} className="mb-4" />

      <div className="flex-1 min-h-[360px] space-y-4">
        {/* Tab 1: Model Identity */}
        {activeTab === 'identity' && (
          <div className="space-y-4">
            {/* UC2 Headline Mismatch Banner if applicable */}
            {isMismatch && (
              <div className="p-3.5 bg-[var(--limitation-bg)] border border-[var(--limitation-border)] rounded-[var(--r-md)]">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-[14px]">⚠️</span>
                  <h4 className="text-[13px] font-semibold text-[var(--limitation-ink)]">
                    Model Version Mismatch: {modelId.incomingVersion} against {modelId.configuredProduction}
                  </h4>
                </div>
                <p className="text-[12px] leading-[18px] text-[var(--limitation-ink)]">
                  The result cannot be confirmed as generated by the approved production model. Credge reduces assurance rather than blocking the battery.
                </p>
              </div>
            )}

            {/* Model Identity KeyValues Grid */}
            <div className="p-4 bg-[var(--surface-2)] border border-[var(--rule)] rounded-[var(--r-md)] grid grid-cols-2 sm:grid-cols-3 gap-4">
              <KeyValue
                label="INCOMING MODEL VERSION"
                value={modelId.incomingVersion}
                basis={isMismatch ? 'Mismatch detected' : 'Production release'}
                mono
              />
              <KeyValue
                label="CONFIGURED PRODUCTION MODEL"
                value={modelId.configuredProduction}
                basis="Authorized release target"
                mono
              />
              <div>
                <span className="text-[11px] font-semibold uppercase tracking-[0.06em] text-[var(--ink-3)] block mb-1">
                  MATCH STATE
                </span>
                <span
                  className={`inline-flex items-center px-2 py-0.5 rounded-[var(--r-sm)] text-[12px] font-semibold ${
                    modelId.matches
                      ? 'bg-[var(--assured-bg)] text-[var(--assured-ink)] border border-[var(--assured-border)]'
                      : 'bg-[var(--limitation-bg)] text-[var(--limitation-ink)] border border-[var(--limitation-border)]'
                  }`}
                >
                  {modelId.matches ? 'MATCH (DLL:V2)' : 'MISMATCH (DLL:V1 vs DLL:V2)'}
                </span>
              </div>
              <KeyValue
                label="BATTERY MANUFACTURER"
                value={modelId.manufacturer}
                basis="LG Chem 14S Pack"
              />
              <KeyValue
                label="ASSURANCE ENGINE"
                value={modelId.assuranceEngine}
                basis="Evaluation pipeline"
                mono
              />
              <div>
                <span className="text-[11px] font-semibold uppercase tracking-[0.06em] text-[var(--ink-3)] block mb-1">
                  POLICY SET
                </span>
                <span className="text-[12px] font-mono text-[var(--ink)] block truncate" title={modelId.policySet.join(', ')}>
                  {modelId.policySet.length} statutory & commercial standards
                </span>
              </div>
            </div>

            {/* C7 Cell Voltage Distribution Chart (Centrepiece) */}
            <C7CellVoltageDistribution telemetry={record.telemetry} />
          </div>
        )}

        {/* Tab 2: Assurance Checks */}
        {activeTab === 'checks' && (
          <div className="space-y-3">
            <div className="p-3 bg-[var(--surface-2)] border border-[var(--rule)] rounded-[var(--r-sm)] text-[12px] text-[var(--ink-2)] flex items-center justify-between">
              <span>Evaluating 4 model identity, output range, status consistency, and vector availability gates.</span>
              <span className="font-semibold text-[var(--ink)]">4 Checks Configured</span>
            </div>

            <div className="divide-y divide-[var(--rule)] border border-[var(--rule)] rounded-[var(--r-md)] bg-[var(--surface)] p-1">
              {layer.checks.map(check => (
                <CheckRow key={check.id} check={check} />
              ))}
            </div>
          </div>
        )}

        {/* Tab 3: Supplied Model Card */}
        {activeTab === 'card' && (
          <div className="space-y-4">
            <ProvenanceLine
              provenance="supplied"
              note={modelCard.provenanceNote || 'Supplied by the source system. Not measured or verified by CCE.'}
              className="mb-2"
            />

            <div className="p-4 bg-[var(--surface-2)] border border-[var(--rule)] rounded-[var(--r-md)]">
              <div className="mb-3 pb-2 border-b border-[var(--rule)]">
                <h4 className="text-[13px] font-semibold text-[var(--ink)]">
                  Catalog Specifications & Reported Model Claims
                </h4>
                <p className="text-[11px] text-[var(--ink-3)] mt-0.5">
                  Specifications transcribed from source system documentation. CCE does not evaluate or audit offline claims.
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {modelCard.entries.map((entry, idx) => (
                  <KeyValue
                    key={idx}
                    label={entry.label.toUpperCase()}
                    value={entry.value}
                  />
                ))}
              </div>

              <div className="mt-4 pt-3 border-t border-[var(--rule)] text-[11px] text-[var(--ink-3)] italic">
                {/* TODO: complete entry list */}
                Note: All model metrics are client-supplied catalog specifications and are not CCE-computed indicators.
              </div>
            </div>
          </div>
        )}


        {/* Tab 4: Summary */}
        {activeTab === 'summary' && (
          <div className="space-y-4">
            <div className="p-4 bg-[var(--surface-2)] border border-[var(--rule)] rounded-[var(--r-md)]">
              <div className="flex items-center justify-between mb-2">
                <h4 className="text-[13px] font-semibold text-[var(--ink)]">Layer Purpose & Status</h4>
                <StatusBadge status={layer.result} size="sm" />
              </div>
              <p className="text-[12px] leading-[18px] text-[var(--ink-2)]">
                {layer.purpose}
              </p>
              <div className="mt-3 pt-3 border-t border-[var(--rule)] flex items-center justify-between text-[12px]">
                <span className="text-[var(--ink-3)]">Summary:</span>
                <span className="font-semibold text-[var(--ink)]">{layer.summary}</span>
              </div>
            </div>

            {layer.finding && (
              <div className="p-3 bg-[var(--limitation-bg)] border border-[var(--limitation-border)] rounded-[var(--r-sm)] text-[12px] text-[var(--limitation-ink)]">
                <span className="font-semibold">Finding: </span>
                {layer.finding}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Standing Footer Line (Verbatim) */}
      <div className="mt-6 pt-3 border-t border-[var(--rule)] text-center text-[11px] text-[var(--ink-3)] bg-[var(--surface-2)] -mx-4 -mb-4 px-4 py-2 rounded-b-[var(--r-md)]">
        CCE verifies model identity and output integrity. It does not inspect model internals.
      </div>
    </Panel>
  );
}
